debug: false
# 服务配置信息
server:
  port: ${port:8080}
  context-path: /
  session:
    timeout: 30
    # 服务器session持久性
    persistent: true
    # 服务器session持久性,文件保存路径
#    storeDir:
    # cookie配置
#    cookie:
#      name:
  compression:
    # http response压缩 (默认最小2048 bytes)
    enabled: true
    # 最小压缩大小
#    min-response-size: 2048
    # 压缩类型
#    mime-types:

management:
  port: 8081

# spring配置信息
spring:
  datasource:
    # 是否执行初始化sql文件
#    initialize: true
    # 数据库类型（初始化sql用） schema.sql and data.sql，schema-${platform}.sql and data-${platform}.sql
#    platform: mysql
    # jdbc4不用配置(mysql新版驱动不配置有警告)
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/valuation?useSSL=true&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&k&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false
    username: root
    password: root

    hikari:
      # 默认值 10
      maximum-pool-size: 10

  # spring bath配置
  batch:
    initializer:
      enabled: false

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  jpa:
    show-sql: true
    # 是否自动生成表（DDL）
    generate-ddl: true
    hibernate:
      ddl-auto: update

  devtools:
    remote:
      # 远程自动重启
      secret: mysecret
    restart:
      enabled: true
      trigger-file: .reloadtrigger
    livereload:
      # 触发浏览器刷新
      enabled: true
  main:
    banner-mode: off